S=str(input("Introduceti sirul S: "))
print(S)
#a)
a="A"
print("a) Numarul de litera A=",S.count(a))
#b)
b=S.replace("A","*")
print("b)",b)
#c)
c=S.replace("B"," ")
print("c)",c)
#d)
d="MA"
print("d) Numarul de silabe MA",S.count(d))
#e)
e=S.replace("MA","TA")
print("e)",e)
#f)
f=S.replace("TO"," ")   
print("f)",f)
#g)
print("g)",S[::-1])